import Providers from "@/components/providers/Providers";
import { GlobalStyles } from "@/styles/GlobalStyles";
import { StyledComponentsRegistry } from "@/styles/StyledComponentsRegistry";
import { Roboto_Flex } from "next/font/google";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";
import "react-toastify/dist/ReactToastify.css";
import { theme } from "@/data/theme";

const roboto = Roboto_Flex({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NextTopLoader
          color={theme.palette.secondary[500]}
          initialPosition={0.08}
          crawlSpeed={200}
          height={5}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <Providers>
          <StyledComponentsRegistry>
            <GlobalStyles />
            {children}
          </StyledComponentsRegistry>
        </Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
